package com.badgesystem.servlet;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

@WebServlet("/cgi-bin/verify")
public class CGIVerifyServlet extends HttpServlet {

    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) 
            throws ServletException, IOException {
        
        response.setContentType("text/html;charset=UTF-8");
        String code = request.getParameter("code");
        if (code == null) {
            code = "";
        }

        // 1. Get the absolute path to your Python CGI script
        String pythonScriptPath = getServletContext().getRealPath("/cgi/verify.py");

        // 2. Spawn a new OS process to run Python with full command line argument
        ProcessBuilder pb = new ProcessBuilder("python", pythonScriptPath, code);
        Process process = pb.start();

        // 3. Read output generated by Python (stdout)
        StringBuilder output = new StringBuilder();
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
            String line;
            while ((line = reader.readLine()) != null) {
                // Strip Content-Type header if printed by Python
                if (!line.startsWith("Content-Type:")) {
                    output.append(line).append("\n");
                }
            }
        }

        // 4. Read error stream (stderr) to catch Python execution failures
        StringBuilder errorOutput = new StringBuilder();
        try (BufferedReader errorReader = new BufferedReader(new InputStreamReader(process.getErrorStream()))) {
            String errorLine;
            while ((errorLine = errorReader.readLine()) != null) {
                errorOutput.append(errorLine).append("<br>");
            }
        }

        // 5. Render output or display Python Runtime Error details
        if (errorOutput.length() > 0) {
            response.getWriter().write("<div style='color:red; font-family:sans-serif; padding:15px; border:1px solid red;'>" +
                    "<h3>Python Process Execution Error</h3>" + errorOutput.toString() + "</div>");
        } else {
            response.getWriter().write(output.toString());
        }
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) 
            throws ServletException, IOException {
        doGet(request, response);
    }
}